CREATE TABLE DIM_ENSINO_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, TPO_ESC_ENS_FDM_DET VARCHAR(60)
, TPO_ENS_ESC_ENS_FDM_DET VARCHAR(120)
, TRN_ENS_FDM VARCHAR(50)
, ANO_CCL_ENS_MED VARCHAR(20)
, SIT_CCL_ENS_MED VARCHAR(100)
, TPO_ESC_ENS_MED VARCHAR(60)
, TPO_ESC_ENS_MED_DET VARCHAR(60)
, TPO_ENS_ESC_ENS_MED VARCHAR(120)
, TPO_ENS_ESC_ENS_MED_DET VARCHAR(120)
, TRN_ENS_MED VARCHAR(50)
, FL_SOL_CTF_ENS_MED VARCHAR(3)
, NOM_ENT_CTF VARCHAR(120)
)
;