CREATE TABLE DIM_RECURSO_DIFERENCIADO_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, FL_ACS INT
, FL_AMP INT
, FL_APO_PRN INT
, FL_BRL INT
, FL_CAD_ACO INT
, FL_CAD_CAN INT
, FL_CAD_ESP INT
, FL_GUI_INT INT
, FL_LAM_OVL INT
, FL_LBR INT
, FL_LDR INT
, FL_LTR_LBL INT
, FL_MAQ_BRL INT
, FL_MOB_EPF INT
, FL_MOB_OBS INT
, FL_MSA_CAD_SPA INT
, FL_MTR_EPF INT
, FL_PRV_DTD INT
, FL_SEM_RCS INT
, FL_SLA_ACP INT
, FL_SLA_ESP INT
, FL_SLA_IND INT
, FL_SOL_CMP INT
, FL_SRB INT
, FL_TMP_ADC INT
, FL_TRC INT
, FL_UND_HSP INT
, FL_UND_PRI INT
)
;