CREATE TABLE FAT_NOTA_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, NOT_CIE_HUM FLOAT
, NOT_CIE_NAT FLOAT
, NOT_MAT FLOAT
, TPO_LNG_ESTG INT
, DSC_TPO_LNG_ESTG VARCHAR(20)
, NOT_LNG_COD FLOAT
, COD_SIT_RDC INT
, DSC_SIT_RDC VARCHAR(50)
, NOT_RDC_CPT_1 FLOAT
, NOT_RDC_CPT_2 FLOAT
, NOT_RDC_CPT_3 FLOAT
, NOT_RDC_CPT_4 FLOAT
, NOT_RDC_CPT_5 FLOAT
, NOT_RDC FLOAT
, NOT_MED FLOAT
)
;