CREATE TABLE DIM_CADASTRAL_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, IDD_INS INT
, COD_SEX INT
, DSC_SEX VARCHAR(20)
, COR_RCA INT
, DSC_RCA VARCHAR(50)
, COD_EST_CVL INT
, DSC_EST_CVL VARCHAR(50)
, COD_NAC INT
, DSC_NAC VARCHAR(50)
, COD_MUN_NSC VARCHAR(7)
, COD_MUN_RSD VARCHAR(7)
, FL_IDS VARCHAR(3)
, FL_NOM_SCL VARCHAR(3)
, FL_INS_TRE VARCHAR(3)
)
;