CREATE TABLE DIM_CONDICAO_ESPECIAL_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, FL_AUT INT
, FL_BXA_VIS INT
, FL_CEG INT
, FL_DEF_AUD INT
, FL_DEF_FIS INT
, FL_DEF_MTL INT
, FL_DFC_ATC INT
, FL_DIS INT
, FL_DLX INT
, FL_GST INT
, FL_LAC INT
, FL_MDC INT
, FL_MDD_GLC INT
, FL_MRC_PSS INT
, FL_MSA_CAD_RDA INT
, FL_OUT_DEF INT
, FL_PTT_AUR INT
, FL_SBT INT
, FL_SDZ INT
, FL_SDZ_CEG INT
, FL_SND INT
, FL_VIS_MON INT
)
;