CREATE TABLE DIM_ESCOLA_RR
(
  NUM_INS VARCHAR(12) PRIMARY KEY
, ANO_ENEM VARCHAR(4)
, COD_ESC VARCHAR(8)
, COD_TPO_LCL_ESC INT
, DSC_TPO_LCL_ESC VARCHAR(50)
, FL_SIT_FUN_ESC INT
, DSC_SIT_FUN_ESC VARCHAR(50)
, FL_DPD_ADM_ESC INT
, DSC_DPD_ADM_ESC VARCHAR(20)
, COD_MUN_ESC VARCHAR(7)
)
;